import * as THREE from 'three';

const $=s=>document.querySelector(s),game=$('#game'),levelLabel=$('#levelLabel'),speedLabel=$('#speedLabel'),bestLabel=$('#bestLabel'),progressFill=$('#progressFill'),hint=$('#targetHint'),toast=$('#toast'),startScreen=$('#startScreen'),finishScreen=$('#finishScreen'),finishTime=$('#finishTime'),pauseButton=$('#pauseButton'),pauseScreen=$('#pauseScreen'),resumeButton=$('#resumeButton'),restartButton=$('#restartButton');
const scene=new THREE.Scene();scene.background=new THREE.Color(0x8ed8ff);scene.fog=new THREE.Fog(0x8ed8ff,55,230);
const camera=new THREE.PerspectiveCamera(62,innerWidth/innerHeight,.1,400),renderer=new THREE.WebGLRenderer({antialias:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.setSize(innerWidth,innerHeight);renderer.shadowMap.enabled=true;renderer.domElement.style.touchAction='none';game.appendChild(renderer.domElement);
scene.add(new THREE.HemisphereLight(0xffffff,0x58738d,2.2));const sun=new THREE.DirectionalLight(0xffffff,2.3);sun.position.set(-16,38,-10);sun.castShadow=true;scene.add(sun);
const mat=c=>new THREE.MeshStandardMaterial({color:c,roughness:.72}),roofMats=[mat(0x58b9a6),mat(0x6b77c8),mat(0xf19a66),mat(0x8e70bd)],hazardMat=mat(0xe84d5b),movingMat=mat(0xff784f),cityMat=mat(0x7896a8),world=new THREE.Group();scene.add(world);
const anchors=[],roofs=[],hazards=[],movers=[],checkpoints=[],rivals=[];let targetAnchor=null;
function box(x,y,z,w,h,d,m,parent=world){const o=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),m);o.position.set(x,y,z);o.castShadow=o.receiveShadow=true;parent.add(o);return o}
function roof(x,y,z,w=16,d=16){box(x,y-2,z,w,4,d,roofMats[roofs.length%4]);roofs.push({x,y,z,w,d})}
function anchor(x,y,z){const m=new THREE.MeshStandardMaterial({color:0xffe14d,emissive:0xffb800,emissiveIntensity:2.4,roughness:.3}),o=new THREE.Mesh(new THREE.SphereGeometry(.82,18,14),m);o.position.set(x,y,z);world.add(o);anchors.push(o)}
function hazard(x,y,z,w,h,d){const o=box(x,y,z,w,h,d,hazardMat);hazards.push({mesh:o,w,h,d})}
function mover(x,y,z,w,h,d,axis='x',range=4,speed=1){const o=box(x,y,z,w,h,d,movingMat),m={mesh:o,w,h,d,axis,range,speed,base:o.position.clone(),phase:movers.length*1.37};movers.push(m);hazards.push({...m,moving:true})}
function checkpoint(x,y,z){checkpoints.push({z:z+2,p:new THREE.Vector3(x,y+1.15,z)})}
function finish(x,y,z){const r=new THREE.Mesh(new THREE.TorusGeometry(4.5,.45,12,36),mat(0xffdf45));r.rotation.y=Math.PI/2;r.position.set(x,y+5.5,z);world.add(r);return z}
function scenery(){for(let z=10;z<230;z+=22)for(const side of[-1,1]){const x=side*(22+(z%44?4:0)),h=10+(z*7)%22;box(x,h/2-5,z,13,h,15,cityMat)}}
function rival(color,x,z,pace){const g=new THREE.Group(),b=new THREE.Mesh(new THREE.CapsuleGeometry(.48,.9,5,8),mat(color)),h=new THREE.Mesh(new THREE.SphereGeometry(.37,12,10),mat(0xffbd8b));h.position.y=1.08;g.add(b,h);g.position.set(x,1.05,z);world.add(g);rivals.push({g,pace,bob:Math.random()*6.2})}
function buildLevel(L){while(world.children.length)world.remove(world.children[0]);anchors.length=roofs.length=hazards.length=movers.length=checkpoints.length=rivals.length=0;targetAnchor=null;scenery();if(L===1){const P=[{x:0,y:0,z:0,w:18,d:28},{x:0,y:0,z:55,w:21,d:24},{x:0,y:1.5,z:103,w:19,d:22},{x:0,y:3,z:158,w:21,d:24},{x:0,y:4,z:211,w:23,d:28}];P.forEach(p=>{roof(p.x,p.y,p.z,p.w,p.d);checkpoint(p.x,p.y,p.z)});anchor(0,13.5,32);anchor(0,16.5,82);anchor(0,19,132);anchor(0,20,185);hazard(-6.5,2.1,101,3,2.2,2.2);hazard(6.4,4,160,3,2.4,2.2);rival(0xff4f7b,-2.4,8,10.3);rival(0x7dff6a,2.5,3,10);rival(0x6f79ff,.8,13,10.6);return finish(0,4,225)}const count=7+Math.min(4,Math.floor(L/2)),step=38;let lane=0,y=0;for(let i=0;i<count;i++){const z=i*step;if(i&&L>=4)lane=THREE.MathUtils.clamp(lane+(i%4<2?2:-2),-4,4);roof(lane,y,z,18,17);checkpoint(lane,y,z);if(i<count-1){anchor(lane,y+14+(i%3),z+20);if(L>=3&&i%3===1)hazard(lane+5,y+2.2,z+9,2.5,4.4,1.5);if(L>=5&&i%3===0)mover(lane,y+2.1,z+10,2.5,3.8,1.8,'x',3.5,.8)}}return finish(lane,y,(count-1)*step+8)}
const player=new THREE.Group(),body=new THREE.Mesh(new THREE.CapsuleGeometry(.62,1.15,6,10),mat(0x222633)),head=new THREE.Mesh(new THREE.SphereGeometry(.48,16,12),mat(0xffb77d));head.position.y=1.35;body.castShadow=head.castShadow=true;player.add(body,head);scene.add(player);
const rope=new THREE.Line(new THREE.BufferGeometry().setFromPoints([new THREE.Vector3(),new THREE.Vector3()]),new THREE.LineBasicMaterial({color:0xffffff,transparent:true,opacity:.95}));rope.visible=false;scene.add(rope);
const pos=player.position,vel=new THREE.Vector3(),cp=new THREE.Vector3();let running=false,respawning=false,grappling=false,currentAnchor=null,ropeLength=0,level=1,finishZ=0,startT=0,lastCheckpointZ=-Infinity,grappleCount=0,pointerHeld=false,pointerId=null,grounded=false,releaseCueShown=false,releaseReady=false,lastReleaseWindowAt=0,grappleBuffered=false,flowStreak=0,feelPulse=0,spawnGraceUntil=0,paused=false,pauseStartedAt=0,pausedTotal=0,hiddenStartedAt=0;
const BASE=8.7,MAX=11.6,GRAVITY=23.5,SOFT=8,HARD=10.5,AIR=.9992;
function anchorVisual(a,selected,attached=false){if(!a)return;const s=attached?(releaseReady?1.55:1.42):selected?1.24:1;a.scale.lerp(new THREE.Vector3(s,s,s),.25);a.material.emissiveIntensity=attached?(releaseReady?6.5:5):selected?3.7:2.4;a.material.emissive.setHex(attached&&releaseReady?0x35ff85:0xffb800)}
function chooseTarget(){let best=null,score=999;for(const a of anchors){const o=a.position.clone().sub(pos),dz=o.z;if(dz<2||dz>45)continue;const d=o.length();if(d>48)continue;const s=d+Math.abs(o.x)*.7;if(s<score){score=s;best=a}}return best}
function updateTarget(){const n=grappling?currentAnchor:chooseTarget();if(n!==targetAnchor){if(targetAnchor&&targetAnchor!==currentAnchor)anchorVisual(targetAnchor,false);targetAnchor=n}for(const a of anchors)anchorVisual(a,a===targetAnchor,grappling&&a===currentAnchor)}
function attach(){if(!running||respawning||paused||grappling)return;const a=chooseTarget();if(!a){grappleBuffered=pointerHeld;return}grappleBuffered=false;currentAnchor=a;grappling=true;grappleCount++;releaseCueShown=releaseReady=false;lastReleaseWindowAt=0;ropeLength=THREE.MathUtils.clamp(pos.distanceTo(a.position),8,25);rope.visible=true;if(grounded)vel.y=Math.min(vel.y,-.35);navigator.vibrate?.(10)}
function detach(user=false){if(!grappling)return;const perfect=user&&(releaseReady||performance.now()-lastReleaseWindowAt<130);grappling=false;rope.visible=false;rope.material.color.setHex(0xffffff);if(currentAnchor){currentAnchor.material.emissive.setHex(0xffb800);currentAnchor.material.emissiveIntensity=2.4}currentAnchor=null;releaseReady=releaseCueShown=false;lastReleaseWindowAt=0;if(perfect){flowStreak++;feelPulse=1;toast.textContent=flowStreak>1?`PERFECT ×${flowStreak}`:'PERFECT RELEASE';navigator.vibrate?.([7,18,10]);setTimeout(()=>{if(toast.textContent.startsWith('PERFECT'))toast.textContent=''},380)}else if(user)flowStreak=0}
function reset(){detach(false);pos.copy(cp);vel.set(0,0,BASE);grappleBuffered=false;respawning=false;grounded=true;spawnGraceUntil=performance.now()+850}
function groundAt(){let top=-999;for(const r of roofs)if(Math.abs(pos.x-r.x)<r.w/2-.35&&Math.abs(pos.z-r.z)<r.d/2-.35)top=Math.max(top,r.y);return top}
function hit(h){const q=h.mesh.position;return Math.abs(pos.x-q.x)<h.w/2+.32&&Math.abs(pos.z-q.z)<h.d/2+.32&&pos.y+1.7>q.y-h.h/2&&pos.y-1<q.y+h.h/2}
function respawn(msg){if(respawning)return;respawning=true;flowStreak=0;detach(false);toast.textContent=msg;navigator.vibrate?.([20,25,35]);setTimeout(()=>{toast.textContent='';reset()},420)}
function simulate(dt){const wasGrounded=grounded;grounded=false;if(wasGrounded){vel.z=THREE.MathUtils.lerp(vel.z,MAX,1-Math.pow(.018,dt));vel.x*=Math.pow(.7,dt)}else{vel.x*=Math.pow(AIR,dt*60);vel.z*=Math.pow(AIR,dt*60)}vel.y-=GRAVITY*dt;if(grappling&&currentAnchor){const radial=pos.clone().sub(currentAnchor.position),len=Math.max(radial.length(),.001),n=radial.multiplyScalar(1/len),radialSpeed=vel.dot(n);if(radialSpeed>0)vel.addScaledVector(n,-radialSpeed);vel.multiplyScalar(1-dt*.025)}const previousY=vel.y,over=Math.abs(pos.x)-SOFT;if(over>0)vel.x+=-Math.sign(pos.x)*over*5*dt;pos.addScaledVector(vel,dt);if(Math.abs(pos.x)>HARD){pos.x=THREE.MathUtils.clamp(pos.x,-HARD,HARD);if(Math.sign(vel.x)===Math.sign(pos.x))vel.x*=.25}if(grappling&&currentAnchor){const radial=pos.clone().sub(currentAnchor.position),d=Math.max(radial.length(),.001),n=radial.multiplyScalar(1/d);if(d>ropeLength){pos.copy(currentAnchor.position).addScaledVector(n,ropeLength);const radialSpeed=vel.dot(n);if(radialSpeed>0)vel.addScaledVector(n,-radialSpeed)}if(currentAnchor.position.z<pos.z-9)detach(false)}const g=groundAt();if(g>-900&&pos.y<=g+1.15&&vel.y<=0){const impact=Math.abs(previousY);pos.y=g+1.15;vel.y=0;grounded=true;if(!wasGrounded&&impact>2.5&&impact<10&&vel.z>7&&!toast.textContent){toast.textContent=flowStreak?`SMOOTH · FLOW ×${flowStreak}`:'SMOOTH LANDING';setTimeout(()=>{if(toast.textContent.startsWith('SMOOTH'))toast.textContent=''},300)}else if(impact>15){vel.z*=.9;flowStreak=0}for(const c of checkpoints)if(c.z>lastCheckpointZ&&pos.z>=c.z){cp.copy(c.p);lastCheckpointZ=c.z}}}
function updateRivals(dt,now){if(level!==1)return;for(const r of rivals){r.g.position.z+=r.pace*dt;r.g.position.y=1.15+Math.abs(Math.sin(now*.008+r.bob))*.14;r.g.rotation.z=Math.sin(now*.006+r.bob)*.05;if(r.g.position.z>finishZ+8)r.g.visible=false}}
function update(dt,now){if(!running||respawning||paused)return;for(const m of movers)m.mesh.position[m.axis]=m.base[m.axis]+Math.sin(now*.001*m.speed+m.phase)*m.range;updateRivals(dt,now);for(let i=0;i<5;i++){simulate(dt/5);if(pos.y<-13){respawn('MISSED!');return}if(now>spawnGraceUntil)for(const h of hazards)if(hit(h)){respawn('CRASH!');return}}updateTarget();if(grappleBuffered&&pointerHeld&&!grappling&&targetAnchor)attach();if(grappling&&currentAnchor){const radial=pos.clone().sub(currentAnchor.position),rz=radial.z,speed=vel.length();releaseReady=rz>0&&rz<8&&vel.y>1&&vel.z>7.5&&speed>10;if(releaseReady)lastReleaseWindowAt=performance.now();rope.material.color.setHex(releaseReady?0xa7ffbf:0xffffff);if(releaseReady&&!releaseCueShown){releaseCueShown=true;navigator.vibrate?.(6)}}else releaseReady=false;if(rope.visible&&currentAnchor)rope.geometry.setFromPoints([pos.clone().add(new THREE.Vector3(0,.65,0)),currentAnchor.position]);hint.textContent=grappling?(releaseReady?'RELEASE!':'HOLD · DROP · SWING'):targetAnchor?'HOLD TO GRAPPLE':grounded?'SPRINT!':'FLY!';player.rotation.z=THREE.MathUtils.lerp(player.rotation.z,-vel.x*.02,.1);player.rotation.x=THREE.MathUtils.lerp(player.rotation.x,vel.y*.014,.1);const swingSpeed=grappling?Math.max(0,vel.length()-10):0,cam=new THREE.Vector3(pos.x*.9,pos.y+5.9,pos.z-16.5);camera.position.lerp(cam,1-Math.pow(.005,dt));camera.lookAt(pos.x*.84,pos.y+1.9,pos.z+14);feelPulse=Math.max(0,feelPulse-dt*3.8);camera.fov=THREE.MathUtils.lerp(camera.fov,62+swingSpeed*.38+feelPulse*1.8,.055);camera.updateProjectionMatrix();speedLabel.textContent=Math.round(vel.length());progressFill.style.width=`${Math.min(100,Math.max(0,pos.z/finishZ*100))}%`;if(pos.z>finishZ){if(grappleCount<3){respawn('USE THE GRAPPLES');return}running=false;detach(false);const time=(performance.now()-startT-pausedTotal)/1000,key=`grapple-best-${level}`,best=Number(localStorage.getItem(key)||999);if(time<best)localStorage.setItem(key,time);finishTime.textContent=`${time.toFixed(2)}s`;bestLabel.textContent=`${Math.min(time,best).toFixed(2)}s`;finishScreen.classList.add('visible')}}
function startLevel(){level=1;finishZ=buildLevel(level);levelLabel.textContent=`${level}/10`;cp.set(0,1.15,0);lastCheckpointZ=-Infinity;grappleCount=0;flowStreak=0;feelPulse=0;pausedTotal=0;hiddenStartedAt=0;startT=performance.now();running=true;startScreen.classList.remove('visible');finishScreen.classList.remove('visible');pauseScreen.classList.remove('visible');pauseButton.classList.remove('hidden');reset()}
function setPaused(v){if(!running||respawning||paused===v)return;paused=v;pointerHeld=false;grappleBuffered=false;pointerId=null;detach(false);if(v){pauseStartedAt=performance.now();pauseScreen.classList.add('visible');pauseButton.classList.add('hidden')}else{if(pauseStartedAt)pausedTotal+=performance.now()-pauseStartedAt;pauseStartedAt=0;pauseScreen.classList.remove('visible');pauseButton.classList.remove('hidden');last=performance.now()}}
pauseButton.onclick=e=>{e.stopPropagation();setPaused(true)};resumeButton.onclick=e=>{e.stopPropagation();setPaused(false)};restartButton.onclick=e=>{e.stopPropagation();paused=false;pauseScreen.classList.remove('visible');startLevel()};$('#startButton').onclick=startLevel;$('#nextButton').onclick=startLevel;
renderer.domElement.addEventListener('pointerdown',e=>{if(!running||paused||finishScreen.classList.contains('visible'))return;e.preventDefault();pointerHeld=true;grappleBuffered=true;pointerId=e.pointerId;renderer.domElement.setPointerCapture?.(e.pointerId);attach()},{passive:false});function endPointer(e){if(e&&pointerId!==null&&e.pointerId!==pointerId)return;pointerHeld=false;grappleBuffered=false;pointerId=null;detach(true)}renderer.domElement.addEventListener('pointerup',endPointer);renderer.domElement.addEventListener('pointercancel',endPointer);addEventListener('blur',()=>{pointerHeld=false;grappleBuffered=false;pointerId=null;detach(false)});document.addEventListener('visibilitychange',()=>{if(document.hidden){hiddenStartedAt=performance.now();pointerHeld=false;grappleBuffered=false;pointerId=null;detach(false)}else if(hiddenStartedAt){pausedTotal+=performance.now()-hiddenStartedAt;hiddenStartedAt=0;last=performance.now()}});
let last=performance.now();function loop(now){requestAnimationFrame(loop);const dt=Math.min((now-last)/1000,.033);last=now;update(dt,now);player.position.copy(pos);renderer.render(scene,camera)}requestAnimationFrame(loop);addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)});finishZ=buildLevel(1);cp.set(0,1.15,0);reset();camera.position.set(0,6,-15);camera.lookAt(0,2,14);
