import * as THREE from 'three';

const game=document.querySelector('#game'), levelLabel=document.querySelector('#levelLabel'), speedLabel=document.querySelector('#speedLabel'), bestLabel=document.querySelector('#bestLabel'), progressFill=document.querySelector('#progressFill'), hint=document.querySelector('#targetHint'), toast=document.querySelector('#toast'), startScreen=document.querySelector('#startScreen'), finishScreen=document.querySelector('#finishScreen'), finishTime=document.querySelector('#finishTime');
const scene=new THREE.Scene(); scene.background=new THREE.Color(0x8ed8ff); scene.fog=new THREE.Fog(0x8ed8ff,35,135);
const camera=new THREE.PerspectiveCamera(64,innerWidth/innerHeight,.1,300); const renderer=new THREE.WebGLRenderer({antialias:true,powerPreference:'high-performance'}); renderer.setPixelRatio(Math.min(devicePixelRatio,2)); renderer.setSize(innerWidth,innerHeight); renderer.shadowMap.enabled=true; renderer.domElement.style.touchAction='none'; game.appendChild(renderer.domElement);
scene.add(new THREE.HemisphereLight(0xffffff,0x5d7991,2.1)); const sun=new THREE.DirectionalLight(0xffffff,2.4); sun.position.set(-15,35,-15); sun.castShadow=true; scene.add(sun);
const mat=(c)=>new THREE.MeshStandardMaterial({color:c,roughness:.72}); const roofMats=[mat(0x58b9a6),mat(0x6b77c8),mat(0xf19a66),mat(0x8e70bd)];
const world=new THREE.Group(); scene.add(world); const anchors=[]; const roofs=[];
function box(x,y,z,w,h,d,m){const o=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),m);o.position.set(x,y,z);o.receiveShadow=true;world.add(o);roofs.push({x,z,y:y+h/2,w,d});return o}
function build(level=1){while(world.children.length)world.remove(world.children[0]);anchors.length=0;roofs.length=0; const gap=level===1?7:level===2?9:11; for(let i=0;i<13;i++){const z=i*(16+gap);const y=Math.sin(i*.8)*2+(i%4===3?2:0);const w=14+(i%3)*3;box((i%2?2:-2),y-2,z,w,4,16,roofMats[i%roofMats.length]); for(let b=0;b<3;b++){const bh=5+((i+b)%4)*3;box((i%2?2:-2)+(b-1)*5,y+bh/2,z+(b-1)*3,3,bh,3,mat([0x50647a,0x687e93,0x42586e][b]));} if(i<12){const a=new THREE.Mesh(new THREE.SphereGeometry(.65,16,12),new THREE.MeshStandardMaterial({color:0xffe14d,emissive:0xffb800,emissiveIntensity:2}));a.position.set(i%2?5:-5,y+11,z+13);world.add(a);anchors.push(a)}} const finish=new THREE.Mesh(new THREE.TorusGeometry(5,.45,12,36),mat(0xffdf45));finish.rotation.y=Math.PI/2;finish.position.set(0,7,12*(16+gap)+8);world.add(finish); return finish.position.z}
const player=new THREE.Group(); const body=new THREE.Mesh(new THREE.CapsuleGeometry(.62,1.15,6,10),mat(0x222633)); body.castShadow=true; player.add(body); const head=new THREE.Mesh(new THREE.SphereGeometry(.48,16,12),mat(0xffb77d));head.position.y=1.35;player.add(head);scene.add(player);
const ropeGeom=new THREE.BufferGeometry().setFromPoints([new THREE.Vector3(),new THREE.Vector3()]);const rope=new THREE.Line(ropeGeom,new THREE.LineBasicMaterial({color:0xffffff,transparent:true,opacity:.9}));rope.visible=false;scene.add(rope);
let vel=new THREE.Vector3(0,0,10), running=false, grappling=false, anchor=null, ropeLen=0, level=1, finishZ=0, startT=0, checkpoint=new THREE.Vector3(0,3,0), grounded=false, respawning=false, inputHeld=false; const pos=player.position; pos.copy(checkpoint);
function releaseGrapple(boost=false){if(!grappling)return;grappling=false;rope.visible=false;anchor=null;if(boost){vel.z=Math.min(vel.z+1.7,24+level*3);vel.y=Math.max(vel.y+.65,1.1)}}
function reset(){inputHeld=false;releaseGrapple(false);pos.copy(checkpoint);vel.set(0,0,10+level*1.2);grounded=false;respawning=false}
function nearestAnchor(){let best=null,score=1e9;for(const a of anchors){const dz=a.position.z-pos.z;if(dz<1.5||dz>34)continue;const dx=Math.abs(a.position.x-pos.x);if(dx>15)continue;const d=a.position.distanceTo(pos);const s=d+dx*.25+Math.max(0,dz-22)*.18;if(s<score){score=s;best=a}}return best}
function grappleOn(){inputHeld=true;if(!running||grappling||respawning)return;anchor=nearestAnchor();if(!anchor){inputHeld=false;return}grappling=true;ropeLen=THREE.MathUtils.clamp(pos.distanceTo(anchor.position)*.94,5,24);rope.visible=true;if(navigator.vibrate)navigator.vibrate(10)}
function grappleOff(){inputHeld=false;releaseGrapple(true)}
function groundAt(p){let top=-999;for(const r of roofs)if(Math.abs(p.x-r.x)<r.w/2-.25&&Math.abs(p.z-r.z)<r.d/2-.25)top=Math.max(top,r.y);return top}
function respawn(){if(respawning)return;respawning=true;releaseGrapple(false);toast.textContent='TRY AGAIN';setTimeout(()=>{toast.textContent='';reset()},220)}
function update(dt){if(!running)return;const wasGrounded=grounded;grounded=false;vel.y-=22*dt;vel.z+=grounded?5*dt:3.5*dt;vel.z=Math.min(vel.z,20+level*3);
 if(grappling&&anchor){const delta=pos.clone().sub(anchor.position),d=delta.length();if(d>ropeLen){const n=delta.multiplyScalar(1/d);pos.copy(anchor.position).addScaledVector(n,ropeLen);const outward=vel.dot(n);if(outward>0)vel.addScaledVector(n,-outward);const tangentForward=new THREE.Vector3(0,0,1).addScaledVector(n,-n.z).normalize();vel.addScaledVector(tangentForward,5.5*dt)} if(anchor.position.z<pos.z-4)releaseGrapple(false)}
 pos.addScaledVector(vel,dt); const g=groundAt(pos);if(g>-900&&pos.y<=g+1.15&&vel.y<=0){pos.y=g+1.15;vel.y=0;grounded=true;checkpoint.set(pos.x,pos.y,pos.z);vel.x=THREE.MathUtils.lerp(vel.x,-pos.x*.25,1-Math.pow(.08,dt));if(!wasGrounded&&navigator.vibrate)navigator.vibrate(5)}else if(pos.y<-15){respawn();return}
 player.rotation.z=THREE.MathUtils.lerp(player.rotation.z,-vel.x*.025,.1);player.rotation.x=THREE.MathUtils.lerp(player.rotation.x,vel.y*.012,.1); const target=nearestAnchor();hint.textContent=grappling?'RELEASE TO LAUNCH':target?'HOLD TO GRAPPLE':'KEEP RUNNING'; if(rope.visible&&anchor){rope.geometry.setFromPoints([pos.clone().add(new THREE.Vector3(0,.7,0)),anchor.position]);}
 const camTarget=new THREE.Vector3(pos.x*.4,pos.y+5.2,pos.z-12);camera.position.lerp(camTarget,1-Math.pow(.002,dt));camera.lookAt(pos.x*.18,pos.y+2,pos.z+9);camera.fov=THREE.MathUtils.lerp(camera.fov,64+Math.max(0,vel.z-12)*.45,.06);camera.updateProjectionMatrix();speedLabel.textContent=Math.round(vel.length());progressFill.style.width=`${Math.min(100,Math.max(0,pos.z/finishZ*100))}%`;
 if(pos.z>finishZ){running=false;releaseGrapple(false);const t=(performance.now()-startT)/1000;finishTime.textContent=t.toFixed(2)+'s';const key='grapple-best-'+level,b=Number(localStorage.getItem(key)||999);if(t<b)localStorage.setItem(key,t);bestLabel.textContent=Math.min(t,b).toFixed(2)+'s';finishScreen.classList.add('visible')}}
function start(){startScreen.classList.remove('visible');finishScreen.classList.remove('visible');finishZ=build(level);checkpoint.set(0,3,0);reset();levelLabel.textContent=level;const b=localStorage.getItem('grapple-best-'+level);bestLabel.textContent=b?Number(b).toFixed(2)+'s':'--';startT=performance.now();running=true}
document.querySelector('#startButton').onclick=start;document.querySelector('#nextButton').onclick=()=>{level=level%3+1;start()};
renderer.domElement.addEventListener('pointerdown',e=>{e.preventDefault();renderer.domElement.setPointerCapture?.(e.pointerId);grappleOn()},{passive:false});renderer.domElement.addEventListener('pointerup',e=>{e.preventDefault();grappleOff()},{passive:false});renderer.domElement.addEventListener('pointercancel',grappleOff);renderer.domElement.addEventListener('contextmenu',e=>e.preventDefault());
addEventListener('keydown',e=>{if(e.code==='Space'&&!e.repeat){e.preventDefault();grappleOn()}});addEventListener('keyup',e=>{if(e.code==='Space'){e.preventDefault();grappleOff()}});addEventListener('blur',()=>{inputHeld=false;releaseGrapple(false)});document.addEventListener('visibilitychange',()=>{if(document.hidden){inputHeld=false;releaseGrapple(false)}});addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)});
finishZ=build(1);camera.position.set(0,8,-12);camera.lookAt(0,2,8);let last=performance.now();function loop(now){const dt=Math.min(.025,(now-last)/1000);last=now;update(dt);renderer.render(scene,camera);requestAnimationFrame(loop)}requestAnimationFrame(loop);
